CREATE TABLE IF NOT EXISTS users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     TEXT NOT NULL UNIQUE,
    login     TEXT NOT NULL UNIQUE,
    name      TEXT NOT NULL,
    birthday  DATE
);
CREATE TABLE IF NOT EXISTS mpa_ratings
(
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS films
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    description   TEXT,
    release_date  DATE,
    duration  INT,
    mpa_id     INT NOT NULL REFERENCES mpa_ratings (id),
    CHECK (duration IS NULL OR duration > 0)
);
CREATE TABLE IF NOT EXISTS genres
(
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  BIGINT NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    genre_id INT    NOT NULL REFERENCES genres (id),
    PRIMARY KEY (film_id, genre_id)
);
CREATE TABLE IF NOT EXISTS film_likes
(
    film_id BIGINT NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);
CREATE TABLE IF NOT EXISTS friendships
(
        user_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        friend_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        PRIMARY KEY (user_id, friend_id),
        CHECK (user_id <> friend_id)
);
CREATE INDEX IF NOT EXISTS idx_users_email     ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_login     ON users (login);
CREATE INDEX IF NOT EXISTS idx_films_mpa       ON films (mpa_id);
CREATE INDEX IF NOT EXISTS idx_fg_genre        ON film_genres (genre_id);
CREATE INDEX IF NOT EXISTS idx_likes_film      ON film_likes (film_id);
CREATE INDEX IF NOT EXISTS idx_friend_user     ON friendships (user_id);
CREATE INDEX IF NOT EXISTS idx_friend_friend   ON friendships (friend_id);
